<?php
	// LO SCRIPT PERMETTE L'APERTURA DEL FILE XML IN CUI SONO STATI REGISTRATI TUTTI I DETTAGLI INERENTI ALLE DISCUSSIONI AVVIATE E ALIMENTATE DAGLI UTENTI IN RELAZIONE ALLE PROPOSTE DI VENDITA O, NEL DETTAGLIO, AGLI ARTICOLI A CUI QUESTE SI RIFERISCONO 
	// LA MODALITÀ TRAMITE CUI È POSSIBILE INTERAGIRE CON LA STRUTTURA DATI CONSISTE NEL FORMATTARE IL CONTENUTO DI QUEST'ULTIMA COME SE FOSSE UN'UNICA STRINGA PRIVA DI SPAZI BIANCHI E ALTRI ELEMENTI, QUALI, AD ESEMPIO, "\n"
	// UNA VOLTA EFFETTUATO IL PARSING SULLA COMPONENTE OTTENUTA A SEGUITO DELLA PRECEDENTE OPERAZIONE, SI PROCEDE CON LA RICERCA DELLA RADICE DEL DOCUMENTO E DI TUTTI I SUOI NODI FIGLI, I QUALI VERRANNO DISPOSTI, E DUNQUE ORGANIZZATI, ALL'INTERNO DI UN VETTORE CHE TORNERÀ UTILE PER TUTTE QUELLE OPERAZIONI CHE LI COINVOLGERANNO
	// IN OGNI CASO, UNA SIMILE PROCEDURA ASSUMERÀ UN RUOLO CHIAVE IN QUEI CONTESTI IN CUI È PREVISTO IL REPERIMENTO O L'ADEGUAMENTO DELLE INFORMAZIONI RELATIVE ALLE ENTITÀ RAPPRESENTATE DALL'OGGETTO IN QUESTIONE
	
	$xmlStringDiscussioni = "";
		
	foreach ( file("../../XML/Discussioni.xml") as $nodoDiscussioni ) 
	{
		$xmlStringDiscussioni .= trim($nodoDiscussioni);
	}
	
	$docDiscussioni = new DOMDocument();
	$docDiscussioni->loadXML($xmlStringDiscussioni);
	$rootDiscussioni = $docDiscussioni->documentElement;
	$discussioni = $rootDiscussioni->childNodes;
?>