<?php
	// LO SCRIPT PERMETTE L'APERTURA DEL FILE XML IN CUI SONO STATI MEMORIZZATI TUTTI I DETTAGLI INERENTI ALLE RECENSIONI CHE I PRODOTTI HANNO RICEVUTO NEL CORSO DEL TEMPO DA PARTE DEI VARI UTENTI REGISTRATI SULLA PIATTAFORMA
	// LA MODALITÀ TRAMITE CUI È POSSIBILE INTERAGIRE CON LA STRUTTURA DATI CONSISTE NEL FORMATTARE IL CONTENUTO DI QUEST'ULTIMA COME SE FOSSE UN'UNICA STRINGA PRIVA DI SPAZI BIANCHI E ALTRI ELEMENTI, QUALI, AD ESEMPIO, "\n"
	// UNA VOLTA EFFETTUATO IL PARSING SULLA COMPONENTE OTTENUTA A SEGUITO DELLA PRECEDENTE OPERAZIONE, SI PROCEDE CON LA RICERCA DELLA RADICE DEL DOCUMENTO E DI TUTTI I SUOI NODI FIGLI, I QUALI VERRANNO DISPOSTI, E DUNQUE ORGANIZZATI, ALL'INTERNO DI UN VETTORE CHE TORNERÀ UTILE PER TUTTE QUELLE OPERAZIONI CHE LI COINVOLGERANNO
	// IN OGNI CASO, UNA SIMILE PROCEDURA ASSUMERÀ UN RUOLO CHIAVE IN QUEI CONTESTI IN CUI È PREVISTO IL REPERIMENTO O L'ADEGUAMENTO DELLE INFORMAZIONI RELATIVE ALLE ENTITÀ RAPPRESENTATE DALL'OGGETTO IN QUESTIONE
	
	$xmlStringRecensioni = "";
		
	foreach ( file("../../XML/Recensioni_Prodotti.xml") as $nodoRecensioni ) 
	{
		$xmlStringRecensioni .= trim($nodoRecensioni);
	}
	
	$docRecensioni = new DOMDocument();	
	$docRecensioni->loadXML($xmlStringRecensioni);
	$rootRecensioni = $docRecensioni->documentElement;
	$recensioni = $rootRecensioni->childNodes;
?>