<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DEL NUMERO DI SEGNALAZIONI INOLTRATE DAI VARI CLIENTI
	
	// LE INFORMAZIONI CHE SARANNO POI ELABORATE NEI VARI PUNTI DEL CODICE POTRANNO ESSERE REPERITE DALLE RELATIVE STRUTTURE DATI (FILE XML), IL CUI CONTENUTO SARÀ RESO ACCESSIBILE MEDIANTE UNA SERIE DI SCRIPT    
	require_once("./apertura_file_segnalazioni.php");
	
	// AL FINE DI POTERLE QUANTIFICARE CON ESATTEZZA, È STATO NECESSARIO INTRODURRE UN CONTATORE CHE, OLTRE AD ESSERE INIZIALIZZATO A ZERO, VERRÀ INCREMENTATO AD OGNI NUOVA VOCE D'INTERESSE, OVVERO NON ANCORA SOTTOPOSTA ALL'ATTENZIONE DELLE FIGURE DI SPICCO DELLA PIATTAFORMA
	$num_segnalazioni=0;
	
	for($i=0; $i<$segnalazioni->length; $i++){
		$segnalazione=$segnalazioni->item($i);
		
		if($segnalazione->getAttribute("seen")=="No")
			$num_segnalazioni++;
	}
?>