<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DELLE PROPOSTE DI VENDITA CHE COMPONGONO IL DOCUMENTO LORO DEDICATO MEDIANTE L'UTILIZZO DI UNA VARIABILE A CUI VERRÀ ASSEGNATO IL QUANTITATIVO DEI NODI FIGLI DELL'ELEMENTO RADICE  
	$num_offerte=$offerte->length;
?>