<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DEL NUMERO DI DOMANDE INOLTRATE DAI VARI CLIENTI PER IL RECUPERO DELLA LORO PAROLA CHIAVE
	
	// LE INFORMAZIONI CHE SARANNO POI ELABORATE NEI VARI PUNTI DEL CODICE POTRANNO ESSERE REPERITE DALLE RELATIVE STRUTTURE DATI (FILE XML), IL CUI CONTENUTO SARÀ RESO ACCESSIBILE MEDIANTE UNA SERIE DI SCRIPT    
	require_once("./apertura_file_domande_assistenza.php");
	
	// AL FINE DI POTERLE QUANTIFICARE CON ESATTEZZA, È STATO NECESSARIO INTRODURRE UN CONTATORE CHE, OLTRE AD ESSERE INIZIALIZZATO A ZERO, VERRÀ INCREMENTATO AD OGNI NUOVA VOCE D'INTERESSE, OVVERO NON ANCORA SOTTOPOSTA ALL'ATTENZIONE DELL'AMMINISTRATORE DELLA PIATTAFORMA
	$num_domande=0;
	
	for($i=0; $i<$domande->length; $i++){
		$domanda=$domande->item($i);
		
		if($domanda->getAttribute("seen")=="No")
			$num_domande++;
	}
?>