<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DELLE PROPOSTE DI VENDITA CHE COMPONGONO IL CARRELLO RISERVATO AD UN DETERMINATO CLIENTE, MEDIANTE L'UTILIZZO DI UNA VARIABILE A CUI VERRÀ ASSEGNATO IL TOTALE DEI QUANTITATIVI DELLE VARIE VOCI D'INTERESSE 
	// PER CERCARE DI RENDERE IL CODICE QUANTO PIÙ SPENDIBILE POSSIBILE, ABBIAMO DECISO DI FARNE VARIARE IL COMPORTAMENTO IN FUNZIONE DELLA PROFILAZIONE DELL'UTENTE DI CUI SOPRA
	// INFATTI, CI SI POTRÀ IMBATTERE IN UNA DELLE SEGUENTI CASISTICHE:
	// 1) NELL'EVENTUALITÀ IN CUI L'UTENTE NON SI SIA ANCORA AUTENTICATO MA ABBIA COMUNQUE INSERITO DELLE OFFERTE NEL COOKIE CHE NE IDENTIFICA IL CARRELLO, ALLORA SARÀ POSSIBILE CONSIDERARE LA SOMMA PROGRESSIVA DI TUTTE LE SUE COMPONENTI IN CORRISPONDENZA DELLA CHIAVE "quantitativo"
	// 2) D'ALTRO CANTO, E QUALORA L'UTENTE COINVOLTO RISULTI ESSERE UN CLIENTE, SI POTRÀ FARE RIFERIMENTO AL TOTALE DEI QUANTITATIVI CALCOLATI A PARTIRE DA QUELLI PRESENTI IN CORRISPONDENZA DEGLI ELEMENTI CHE RAPPRESENTANO LE OFFERTE D'INTERESSE ALL'INTERNO DEL RELATIVO FILE XML
	
	$num_prodotti_carrello=0;
	
	if(isset($_SESSION["id_Utente"])) {
		
		// LE INFORMAZIONI CHE SARANNO POI ELABORATE NEI VARI PUNTI DEL CODICE POTRANNO ESSERE REPERITE DALLE RELATIVE STRUTTURE DATI (FILE XML), IL CUI CONTENUTO SARÀ RESO ACCESSIBILE MEDIANTE UNA SERIE DI SCRIPT    
		require_once("./apertura_file_carrelli.php");
		
		
		for($i=0; $i<$carrelli->length; $i++) {
			$carrello=$carrelli->item($i);
		
			if($carrello->getAttribute("idCliente")==$_SESSION["id_Utente"]) {
				break;
			}
		}
		
		for($i=0; $i<$carrello->getElementsByTagName("offerta")->length; $i++) {
			$num_prodotti_carrello+=intval($carrello->getElementsByTagName("offerta")->item($i)->getElementsByTagName("quantitativo")->item(0)->textContent);
		}
	}
	else {
		if(isset($_COOKIE["carrello_Offerte"])) {
			$carrello_Offerte=unserialize($_COOKIE["carrello_Offerte"]);
			
			foreach ($carrello_Offerte as $offerta_carrello) {
				$num_prodotti_carrello+=intval($offerta_carrello["quantitativo"]);
			} 
		}
	}
?>