<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DELLE FAQ CHE COMPONGONO IL DOCUMENTO LORO DEDICATO MEDIANTE L'UTILIZZO DI UNA VARIABILE A CUI VERRÀ ASSEGNATO IL QUANTITATIVO DEI NODI FIGLI DELL'ELEMENTO RADICE  
	$num_faq=$faq->length;
?>