<?php
	// LO SCRIPT PERMETTE DI TENERE TRACCIA DEL NUMERO DI RICHIESTE PER LA RICARICA DEL PORTAFOGLIO INERENTE AI VARI CLIENTI
	
	// AL FINE DI POTERLE QUANTIFICARE CON ESATTEZZA, È STATO NECESSARIO INTRODURRE UN CONTATORE CHE, OLTRE AD ESSERE INIZIALIZZATO A ZERO, VERRÀ INCREMENTATO AD OGNI NUOVA DOMANDA D'INTERESSE, OVVERO NON ANCORA SOTTOPOSTA ALL'ATTENZIONE DELL'AMMINISTRATORE DEL SITO
	$num_richieste=0;
	
	for($i=0; $i<$richieste->length; $i++){
		$richiesta=$richieste->item($i);
		
		if($richiesta->getAttribute("stato")=="In Corso")
			$num_richieste++;
	}
?>