<?php 
	// LO SCRIPT PERMETTE DI RIMUOVERE LA SESSIONE APERTA DALL'UTENTE A SEGUITO DELLA SUA PROFILAZIONE  
	require_once("./session_destruction.php");
	
	// UNA VOLTA EFFETTUATA LA DISCONNESSIONE, SI PROCEDE CON IL REINDIRIZZAMENTO DEL SOGGETTO COINVOLTO VERSO LA SCHERMATA DI LOGIN
	header("Location: login.php");
?>