<?php
	// LO SCRIPT PERMETTE DI MONITORARE LO STATO ATTUALE DEL PROFILO DI UN CERTO CLIENTE ("Ban") QUANDO QUEST'ULTIMO HA GIÀ EFFETTUATO LA PROFILAZIONE
	if(isset($_SESSION["id_Utente"])) {

		// AL FINE DI REPERIRE TUTTE LE INFORMAZIONI DI INTERESSE, IN PARTICOLARE QUELLE RELATIVE AGLI UTENTI, È NECESSARIO FARE RIFERIMENTO AL CODICE IN GRADO DI INSTAURARE UNA CONNESSIONE CON LA BASE DI DATI 
		require_once("./connection.php");
		
		$sql="SELECT Ban FROM $tab WHERE ID=".$_SESSION["id_Utente"]." AND Tipo_Utente='C'";
		$result=mysqli_query($conn, $sql);
		
		while($row=mysqli_fetch_array($result))
			$ban=$row["Ban"];
		
		// SE IL SOGGETTO INTERESSATO È STATO SOSPESO A CAUSA DEL SUO COMPORTAMENTO, VERRÀ AUTOMATICAMENTE INTERROTTA LA SESSIONE CHE LO COINVOLGE STAMPANDO A SCHERMO IL RELATIVO MESSAGGIO D'ERRORE
		if(isset($ban) && $ban=="Y") {
			// PRIMA DI ESSERE DISCONNESSO, SI PREDISPONE UN COOKIE CHE SARÀ USATO COME FLAG PER RIPORTARE L'ACCADUTO AL CLIENTE INTERESSATO
			setcookie("profilo_Sospeso", true);
			
			require_once("./logout.php");
		}
	}
?>