<?php
	// LO SCRIPT PERMETTE DI VERIFICARE SE L'UTENTE HA I PERMESSI NECESSARI PER POTER ACCEDERE ALLA SCHERMATA D'INTERESSE, COLLOCATA ALL'INTERNO DELLA SEZIONE RISERVATA. ALTRIMENTI, VERRÀ REINDIRIZZATO VERSO LA PAGINA INIZIALE DEL SITO
	session_start();
	
	if(!isset($_SESSION["id_Utente"]))
		header ("Location: ./logout.php");
?>