<?php
	// LO SCRIPT PERMETTE DI VERIFICARE SE L'UTENTE HA I PERMESSI NECESSARI PER POTER MANTENERE ATTIVA LA PROPRIA SESSIONE ALL'INTERNO DELLA SCHERMATA D'INTERESSE, LA QUALE RISULTA COLLOCATA ALL'ESTERNO DELLA SEZIONE RISERVATA
	session_start();
	
	// SE NON È STATA AVVIATA ALCUNA SESSIONE, SI PROCEDE CON LA CHIUSURA DI QUELLA AVVIATA PER EFFETTUARE IL CONTROLLO. UNA SIMILE STRATEGIA, POICHÈ IL CONTENUTO DELLA PAGINA DOVRÀ ESSERE VISIBILE A CHIUNQUE (UTENTI PROFILATI O MENO), NON COSTRINGERÀ AL REINDERIZZAMENTO DEL SOGGETTO COINVOLTO VERSO UN'ALTRA SCHERMATA
	if(!isset($_SESSION["id_Utente"])) {
		$_SESSION=array();
		session_destroy();
	}
?>