<?php
	// LO SCRIPT PREVEDE LA RICERCA DI TUTTE QUELLE PROPOSTE DI VENDITA CHE SI RIFERISCONO AI VIDEOGIOCHI CHE SONO STATI PUBBLICATI PIÙ DI RECENTE
	// IL PRIMO PASSO DELL'ALGORITMO DI RICERCA CONSISTE NELL'INIZIALIZZARE UN VETTORE VUOTO, IL QUALE VERRÀ POI RIEMPITO MEDIANTE LE COPPIE FORMATE DALL'IDENTIFICATORE DEL PRODOTTO E L'ANNO DI PUBBLICAZIONE DI QUEST'ULTIMO
	$i_piu_recenti=array();
	
	// PER OGNI VIDEOGIOCO CARATTERIZZATO DA UNA PROPOSTA DI VENDITA ANCORA VALIDA, VERRÀ CREATA UNA NUOVA COMBINAZIONE, LA QUALE, OLTRE AD ESSERE DESCRITTA COME SOPRA, ANDRÀ FORMARE UN NUOVO ELEMENTO DELL'ARRAY IN QUESTIONE   
	for($i=0; $i<$prodotti->length; $i++) {
		$prodotto=$prodotti->item($i);
		
		for($j=0; $j<$offerte->length; $j++) {
			$offerta=$offerte->item($j);
			
			if($offerta->getAttribute("idProdotto")==$prodotto->getAttribute("id") && $prodotto->getElementsByTagName("videogioco")->length!=0) {
				$anno_pubblicazione=$prodotto->getElementsByTagName("annoUscita")->item(0)->textContent;
				
				// AL FINE DI REGISTRARE CORRETTAMENTE L'IDENTIFICATORE DEL PRODOTTO, È STATO NECESSARIO TRATTARLO COME SE FOSSE UNA STRINGA. IN PARTICOLARE, I DUE CARATTERI DELIMITATORI DEL VALORE EFFETTIVO SARANNO RAPPRESENTATI DA DEI SINGOLI APICI
				$i_piu_recenti=array_merge($i_piu_recenti, array("'".$prodotto->getAttribute("id")."'" => $anno_pubblicazione));
			}
		}
	}
	
	// UNA VOLTA INDIVIDUATE E MEMORIZZATE LE VARIE INFORMAZIONI DI INTERESSE, SI PROCEDE CON L'ORDINAMENTO DECRESCENTE IN FUNZIONE DEL CONTENUTO (ANNO DI PUBBLICAZIONE) DELLE VARIE COMPONENTI DEL VETTORE TRAMITE LA FUNZIONE arsort(...), LA QUALE, SPOSTANDO OPPORTUNAMENTE ANCHE LE CHIAVI, CONSENTIÀ DI PRESERVARE TUTTE LE COMBINAZIONI 
	arsort($i_piu_recenti);
	
	// PER PORTARE A TERMINE L'OPERAZIONE, È NECESSARIO ELIMINARE TUTTI GLI ELEMENTI AGGIUNTIVI PER PORTARE LA DIMENSIONE DEL VETTORE AD AL MASSIMO 4 POSIZIONI
	$i=0;
	
	foreach($i_piu_recenti as $chiave => $contenuto) {
		
		if($i>=4){
			unset($i_piu_recenti[$chiave]);
		}
		
		$i++;
		
	}
?>